### ISSUE TITLE
Preview Easter Eggs

### ISSUE THREAD

**Issue by exegeteio** [builders-club/onlythemes#12]
**Describe the solution you'd like**
When displaying the preview of the theme, there should exist an easter egg for folks surfing the themes.  Should create a series of code files in various languages each of which performs a small task with some kind of code joke.

**Example**

```js
export default function commit() {
  Git.commit("Mistakes were made");
};
```

```html
<div id="shirt" data-size="medium" data-background-color="black">
  <div class="we">
    <div class="built">
      <div>
        <div class="city">VS Code</div>
      </div>
    </div>
  </div>
</div>
```

```ruby
class Kid < Person
  attr_reader :size
  def initialize()
    @size = :small
  end
end

kids = Kid.all
kids.each do |kid|
  kid.feed!
end
```

**Comment by exegeteio** [comment]
```php
<?= (!false) ? "Funny" : "Not funny" ?>
```

**Comment by MichaelJolley** [comment]
So I had a thought and forgot to add an issue for it. That's been rectified in #14, but I LOVE the idea of these code samples being runnable and including an Easter egg. We just need to make sure they're long enough to take up most of the editor window, but not so long that they don't fit in the editor window.

**Comment by MichaelJolley** [comment]
I'm going to close this as it will be handled in #14. I think using [@whitep4nth3r 's randomcodegenerator.lol](https://github.com/whitep4nth3r/randomcodegenerator.lol) project would be a perfect fit. Not necessarily a "joke" but "joke-like" code.
