### ISSUE TITLE
Screenshot zoom

### ISSUE THREAD

**Issue by MichaelJolley** [builders-club/onlythemes#23]
Before taking the screenshot of the theme, zoom in a few times to improve the view of the image.

**Comment by MichaelJolley** [comment]
This has become quite the chore. We may need to just go back to increasing the font size for now.

Thoughts @parithon?

**Comment by ulentini** [comment]
Shouldn't be easier to just reduce the screenshot size? Since users are gonna see the thumbnail on a sidebar, a 800x600 screenshot (or 1024x768) should be enough.

**Comment by MichaelJolley** [comment]
Good idea @ulentini. We are now taking images in 800x600 screenshots. As they get re-cataloged this shouldn't be a problem. Thanks for the suggestion.
