### ISSUE TITLE
Standardize theme color data

### ISSUE THREAD

**Issue by MichaelJolley** [builders-club/onlythemes#24]
@parithon please close if I'm incorrect, but I think the object we're saving for a theme is different if the theme is a plist vs json.

Let's define what we want that theme object to look like so we can standardize it from either. I think we'll need that before using ML on the dataset.

**Comment by parithon** [comment]
You're not wrong. I do believe the `colors` property will be available in both cases but I don't have enough knowledge on the other aspects. I'll attempt to do some research.

**Comment by parithon** [comment]
From my limited research, it appears we should collect the following information:
- type
- colors
- tokenColors

If my understanding is correct, `.tmTheme` or TextMate themes should consist of token colors. Therefore, I suggest we populate the end object as:

```
{
   type: 'vs-dark',
   colors: { ... any colors provided by the .json theme }
   tokenColors: { ... any tokenColors provided by the .json theme or the results of the .tmTheme parser }
}
```

It is important to note that the `tokenColors` may point to a `.tmTheme` file (which we should parse) or be an object with the attributes inline.

**Comment by MichaelJolley** [comment]
I agree

**Comment by MichaelJolley** [comment]
After looking through the color options in the API I'm thinking about simplifying what we store to just a dozen colors.
