### ISSUE TITLE
Add icons to the swipe left/right buttons

### ISSUE THREAD

**Issue by cmjchrisjones** [builders-club/onlythemes#30]
**Is your feature request related to a problem? Please describe.**
Feature request to make it easier to identify what swipe left/right means

**Describe the solution you'd like**
Add an icon to the swipe left/right buttons to make it clear what each does 
For example a ❤ for a like and a 💔for a dislike for the uninitiated.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MichaelJolley** [comment]
@all-contributors please add @cmjchrisjones for ideas

**Comment by MichaelJolley** [comment]
@all-contributors please add @ibaldie for design and ideas

**Comment by MichaelJolley** [comment]
Finished in latest release
