### ISSUE TITLE
Feature request: Reset button to clear preferences 

### ISSUE THREAD

**Issue by digital-byte** [builders-club/onlythemes#31]
Enable a reset button to clear previous preferences and start over, similar to what a new user would experience.

**Comment by MichaelJolley** [comment]
I think we can accomplish this fairly easily but generating a new uuid for the user. Thanks for the suggestion!

@all-contributors please add @digital-byte for ideas

**Comment by MichaelJolley** [comment]
Rather than having a button, let's add a command pallet command "Forget my ratings." That should open a prompt to confirm and then update the user specific UUID.
