### ISSUE TITLE
Link title of a theme to the official marketplace site

### ISSUE THREAD

**Issue by andi1984** [builders-club/onlythemes#34]
At

https://github.com/builders-club/onlythemes/blob/94e0ab11e0861a14cf0d4f391d2c4be766b88be9/extension/src/onlyThemesView.ts#L133

we could probably link to the theme's official marketplace page. Or at least putting the direct link to the marketplace somewhere in the web view to reduce the amount of manual copy & pasting theme name around.

What do you think?

**Comment by MichaelJolley** [comment]
@all-contributors please add @andi1984 for ideas

**Comment by MichaelJolley** [comment]
Good suggestion.

There's now a 🔗 icon that links the user to the extensions page on the marketplace.

![image](https://user-images.githubusercontent.com/1228996/116421363-60a9ac00-a804-11eb-890e-6278780cc24c.png)
