### ISSUE TITLE
When a recommended theme is already installed, and user selects to install it, causes the extension to hang

### ISSUE THREAD

**Issue by cmjchrisjones** [builders-club/onlythemes#47]
**Describe the bug**
User already has an installed theme that is being recommended and attempts to install it, this causes VS Code to hang

**Expected behaviour**
Don't recommend themes that a user already has installed

**Screenshots**
Video of problem: https://clips.twitch.tv/FrozenSaltyLarkImGlitch-KMy6nn5AJNDbCLbC

**Comment by mtfoley** [comment]
@MichaelJolley @cmjchrisjones I tried to fix this in PR #53 . It's a bit tricky to test since the suggestions are randomized, so on my local copy before pushing, I hardcoded `this.theme.extensionName` to something I already had and made sure the code recognized the theme as already installed.
